name: Test

on: push

jobs:
  yath:
    strategy:
      matrix:
        container: [ "perl:5.36", "perl:5.34", "perl:5.32", "perl:5.30" ]
    container:
      image: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cpanm --quiet --notest --installdeps .
      - run: yath test --qvf t/
